name: Build Frontend Artifacts Test
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering
permissions:
  contents: read
  actions: read

env:
  JFROG_CLI_BUILD_NAME: GHA-NPM-Test
  JF_URL: ${{ vars.JF_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JFrog CLI with Access Token
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }} # Ensure this secret is correctly configured in GitHub
        with:
          version: 'latest'

      - name: Jfrog Configure npm (Access Token)
        run: |
          # The default behavior when --global is omitted is to write .npmrc to the current working directory.
          # We ensure the command runs in the repository root using working-directory.
          jfrog npm-config --repo-resolve=npm-virtual --repo-deploy=npm-local
        working-directory: ${{ github.workspace }} # <--- IMPORTANT: Run this command in the repo root

      - name: Verify npm config
        run: cat ./.npmrc # <--- IMPORTANT: Look for .npmrc in the current directory (repo root)
        working-directory: ${{ github.workspace }}

      - name: Install dependencies (Access Token)
        run: jf npm ci
        working-directory: ${{ github.workspace }}