name: Build Frontend Artifacts Test
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering
permissions:
  contents: read
  actions: read

env:
  JFROG_CLI_BUILD_NAME: GHA-NPM-Test
  JF_URL: ${{ vars.JF_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JFrog CLI with Access Token
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          version: 'latest'

      - name: Debug Working Directory before npm-config
        run: |
          echo "Current working directory: $(pwd)"
          echo "Content of current directory before npm-config:"
          ls -la .
        working-directory: ${{ github.workspace }} # Ensure we're in the repo root

      - name: Jfrog Configure npm (Access Token)
        run: |
          # Use the default behavior: .npmrc written to current working directory
          jfrog npm-config --repo-resolve=npm-virtual --repo-deploy=npm-local
        working-directory: ${{ github.workspace }} # This is essential

      - name: Verify npm config and filesystem state
        run: |
          echo "Current working directory for verification: $(pwd)"
          echo "--- Listing files in current directory AFTER npm-config ---"
          ls -la .
          echo "--- Contents of ./.npmrc (if it exists) ---"
          cat ./.npmrc || echo "Error: ./.npmrc not found after creation attempt."
          echo "--- NPM config list (global and local) ---"
          npm config list --location=global
          npm config list --location=project
          npm config list --location=user
          npm config list # effective configuration
        working-directory: ${{ github.workspace }}

      - name: Install dependencies (Access Token)
        run: jf npm ci
        working-directory: ${{ github.workspace }}